### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [MartinCabreraG/ProyectoFinalBioinf2017-II#1]
OK

Sólo te recuerdo que aunque sean micros quiero que los análisis los hagas con paquetes de R u otras herramientas pero que funcionen via línea de comando.

**Comment by MartinCabreraG** [comment]
OK

Gracias Alicia, haré que funcione todo desde la línea de comando y me pondré buzo con R principalmente.

**Comment by AliciaMstt** [comment]
OK, ya puedes cerrar este issue.

**Comment by AzaleaGuerra** [comment]
¡Muy bien!

**Comment by MartinCabreraG** [comment]
Gracias a ambas.
